name: Check python code

on: [push]

jobs:
  check-python-scripts:
    name: Check python scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
    - name: Lint with flake8
      run: |
        pip install flake8 flake8-docstrings
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --statistics
    - name: Run unit tests
      env:
        JIRA_SERVER: https://example.com
        JIRA_ID: jira@example.com
        JIRA_TOKEN: abcdef
      run: |
        pipenv install
        pipenv run pytest
