name: Deploy worklog summary notifier lambda

on:
  push:
    branches:
    - master
    paths:
    - worklog_notifier_lambda/**
    - worklog_aggregator/**
    - .github/workflows/deploy_lambda.yml
jobs:
  deploy-lambda:
    name: Deploy lambda
    runs-on: ubuntu-latest
    env:
      LAMBDA_DIR: worklog_notifier_lambda
      FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      with:
        path: '**/packages'
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Create zip
      run: |
        pip install -U pip
        cd "${GITHUB_WORKSPACE}/${LAMBDA_DIR}"
        mkdir -p packages
        cd packages
        pip install -r ../requirements.txt --target .
        zip -r9 ../function.zip .
        cd "${GITHUB_WORKSPACE}/${LAMBDA_DIR}"
        zip -g function.zip worklog_summary_notifier.py
        cd "${GITHUB_WORKSPACE}"
        zip -g ${GITHUB_WORKSPACE}/${LAMBDA_DIR}/function.zip -r worklog_aggregator
    - name: Update function
      run: |
        aws lambda update-function-code \
          --function-name "${FUNCTION_NAME}" \
          --zip-file "fileb://${GITHUB_WORKSPACE}/${LAMBDA_DIR}/function.zip" > /dev/null 2>&1
