on:
  push:
    branches:
    - master
    paths:
    - lambda/**
    - worklog_aggregator/**
    - .github/workflows/deploy_lambda.yml
jobs:
  deploy-lambda:
    name: Deploy lambda
    runs-on: ubuntu-latest
    env:
      LAMBDA_DIR: lambda
      FUNCTION_NAME: ${{ secrets.FUNCTION_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Create zip
      run: |
        pip install -U pip
        cd "${GITHUB_WORKSPACE}/${LAMBDA_DIR}"
        mkdir packages
        cd packages
        pip install -r ../../requirements.txt --target .
        zip -r9 ../function.zip .
        cd "${GITHUB_WORKSPACE}/${LAMBDA_DIR}"
        zip -g function.zip lambda.py
        cd "${GITHUB_WORKSPACE}"
        zip -g lambda/function.zip -r worklog_aggregator
    - name: Update function
      run: |
        aws lambda update-function-code \
          --function-name "${FUNCTION_NAME}" \
          --zip-file "fileb://${GITHUB_WORKSPACE}/${LAMBDA_DIR}/function.zip" > /dev/null
